name: feelcast
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

isar_version: &isar_version 3.1.8 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  supabase_flutter: ^2.8.4
  supabase_auth_ui: ^0.5.4

  flutter_screenutil: ^5.9.3

  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^7.0.1
  http_certificate_pinning: ^3.0.1

  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  go_router: ^14.8.1
  # isar: ^3.1.0+1
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  flutter_secure_storage: ^9.2.4

  permission_handler: ^11.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

  freezed_annotation: ^2.3.5
  json_annotation: ^4.9.0

  geolocator: ^13.0.4
  flutter_gemini: ^3.0.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  # isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  http_mock_adapter: ^0.6.1
  # isar_generator: ^3.1.0+1
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/weather/
    - assets/image/

flutter_native_splash:
  color: "#ffffff"
  image: "assets/image/logo.png"
  fullscreen: true
  ios_content_mode: scaleAspectFit
  ios: true
  android: true
  color_android: "#ffffff"
  image_android: "assets/image/logo.png"
  android_12:
    color: "#ffffff"
    image: "assets/image/logo_square.png"
  web: false
