name: feelcast
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  supabase_flutter: ^2.8.4
  supabase_auth_ui: ^0.5.4

  flutter_screenutil: ^5.9.3

  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_retry_plus: ^2.0.8
  http_certificate_pinning: ^3.0.1

  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  go_router: ^14.8.1
  isar: ^3.1.0
  flutter_secure_storage: ^9.2.4

  permission_handler: ^11.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  geolocator: ^13.0.4
  flutter_gemini: ^3.0.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/weather/
